CATEDRA/urls.py
from django.urls import path
from django.conf.urls import include, url
from . import views


urlpatterns = [
    path('', views.inicio, name='inicio'),
    path('escuela', views.lista_escuelas, name='lista_escuelas'),
    path('escuela/<int:codigo>/', views.perfil_escuela, name='perfil_escuela'),
    path('escuela/crear', views.crear_escuela, name='crear_escuela'),
    path('escuela/<int:codigo>/editar/', views.escuela_edit, name='escuela_edit'),
    path('escuela/<int:codigo>/personal/crear/', views.crear_personal, name='crear_personal'),
    path('escuela/<int:codigo>/personal/editar/', views.personal_edit, name='personal_edit'),
    path('escuela/<int:codigo>/matricula/crear/', views.crear_matricula, name='crear_matricula'),
    path('escuela/<int:codigo>/matricula/editar/', views.matricula_edit, name='matricula_edit'),
    path('escuela/<int:codigo>/destrezas/crear/', views.crear_destrezas, name='crear_destrezas'),
    path('escuela/<int:codigo>/destrezas/editar/', views.destrezas_edit, name='destrezas_edit'),
    path('escuela/<int:codigo>/actividad/crear/', views.crear_actividad, name='crear_actividad'),
    path('escuela/<int:codigo>/actividad/<int:pk>/editar/', views.actividad_edit, name='actividad_edit'),
    path('cargar_escuelas/', views.cargar_escuelas, name='cargar_escuelas'),
    path('cargar_servicios/', views.cargar_servicios, name='cargar_servicios'),
    path('vendedores', views.lista_vendedores, name='lista_vendedores'),
    path('vendedor/<int:pk>/', views.perfil_vendedor, name='perfil_vendedor'),
    path('vendedor/<int:pk_vendedor>/visita/crear', views.crear_visita, name='crear_visita'),
    path('visita/<int:pk_vendedor>+<int:pk_visita>/editar/', views.visita_edit, name='visita_edit'),
    path('historial_visitas', views.historial_visitas, name='historial_visitas'),
    path('vendedor/<int:pk>/historial_propuestas', views.historial_propuestas, name='historial_propuestas'),
    path('vendedor/<int:pk_vendedor>/propuesta/crear', views.crear_propuesta, name='crear_propuesta'),
    path('vendedor/<int:pk_vendedor>/propuesta/<int:pk_propuesta>/editar', views.propuesta_edit, name='propuesta_edit'),
    path('propuesta/<int:pk_propuesta>/', views.propuesta_detalle, name='propuesta_detalle'),
    path('propuesta/<int:pk_propuesta>/ofrecimiento/<int:pk_ofrecimiento>/borrar', views.borrar_ofrecimiento, name='borrar_ofrecimiento'),
    path('propuesta/<int:pk_propuesta>/ofrecimiento/crear/', views.crear_ofrecimiento, name='crear_ofrecimiento'),
    path('propuesta/<int:pk_propuesta>/ofrecimiento/<int:pk_ofrecimiento>/edit', views.ofrecimiento_edit, name='ofrecimiento_edit'),
    path('propuesta/<int:pk_propuesta>/pdf/', views.propuesta_pdf, name='propuesta_pdf'),
    path('ofrecimientos', views.lista_ofrecimientos, name='lista_ofrecimientos'),
    path('po/<int:numero_po>/', views.po_detalle, name='po_detalle'),
    path('po/<int:numero_po>/factura/crear', views.crear_factura, name='crear_factura'),
    path('po/<int:numero_po>/factura/<int:numero_factura>/editar', views.factura_edit, name='factura_edit'),
    path('po/<int:numero_po>/factura/<int:numero_factura>/borrar', views.borrar_factura, name='borrar_factura'),
    path('propuesta/<int:pk_propuesta>/po/crear/', views.crear_po, name='crear_po'),
    path('propuesta/<int:pk_propuesta>/po/<int:pk_po>/borrar', views.borrar_po, name='borrar_po'),
    path('propuesta/<int:pk_propuesta>/po/<int:pk_po>/edit', views.po_edit, name='po_edit'),
    path('lista_po', views.lista_po, name='lista_po'),
    path('catalogo_servicios', views.catalogo_servicios, name='catalogo_servicios'),
    path('estrategia/<str:estrategia>/ofrecimiento_titulos_json', views.ofrecimiento_titulos_json, name='ofrecimiento_titulos_json'),

]

GEEO/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url('', include('CATEDRA.urls')),
]
"""
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""

CATEDRA/models.py
from django.db import models
from django.utils import timezone
from django.core.validators import RegexValidator
from  datetime import datetime
from django.contrib.auth.models import User
from dal import autocomplete

# Create your models here.

class Servicio(models.Model):
    tipo = models.CharField(max_length=200)
    estrategia = models.CharField(max_length=200)
    titulo = models.CharField(max_length=200)

    def __str__(self):
        return self.tipo + " - " + self.estrategia + " - " + self.titulo


class Municipio(models.Model):
    nombre_choices = (
    ('ADJUNTAS', 'ADJUNTAS'),
    ('AGUADA', 'AGUADA'),
    ('AGUADILLA', 'AGUADILLA'),
    ('AGUAS BUENAS', 'AGUAS BUENAS'),
    ('AGUAS BUENAS', 'AGUAS BUENAS'),
    ('ANASCO', 'ANASCO'),
    ('ARECIBO I', 'ARECIBO I'),
    ('ARECIBO II', 'ARECIBO II'),
    ('ARROYO', 'ARROYO'),
    ('BARCELONETA', 'BARCELONETA'),
    ('BARRANQUITAS', 'BARRANQUITAS'),
    ('BAYAMON I', 'BAYAMON I'),
    ('BAYAMON II', 'BAYAMON II'),
    ('BAYAMON III', 'BAYAMON III'),
    ('CABO ROJO', 'CABO ROJO'),
    ('CAGUAS I', 'CAGUAS I'),
    ('CAGUAS II', 'CAGUAS II'),
    ('CAMUY', 'CAMUY'),
    ('CANOVANAS', 'CANOVANAS'),
    ('CAROLINA I', 'CAROLINA I'),
    ('CAROLINA II', 'CAROLINA II'),
    ('CATANO', 'CATANO'),
    ('CAYEY', 'CAYEY'),
    ('CEIBA', 'CEIBA'),
    ('CIALES', 'CIALES'),
    ('CIDRA', 'CIDRA'),
    ('COAMO', 'COAMO'),
    ('COMERIO', 'COMERIO'),
    ('COROZAL', 'COROZAL'),
    ('CULEBRA', 'CULEBRA'),
    ('DORADO', 'DORADO'),
    ('FAJARDO', 'FAJARDO'),
    ('FLORIDA', 'FLORIDA'),
    ('GUANICA', 'GUANICA'),
    ('GUAYAMA', 'GUAYAMA'),
    ('GUAYANILLA', 'GUAYANILLA'),
    ('GUAYNABO', 'GUAYNABO'),
    ('GURABO', 'GURABO'),
    ('HATILLO', 'HATILLO'),
    ('HORMIGUEROS', 'HORMIGUEROS'),
    ('HUMACAO', 'HUMACAO'),
    ('ISABELA', 'ISABELA'),
    ('JAYUYA', 'JAYUYA'),
    ('JUANA DIAZ', 'JUANA DIAZ'),
    ('JUNCOS', 'JUNCOS'),
    ('LAJAS', 'LAJAS'),
    ('LARES', 'LARES'),
    ('LAS MARIAS', 'LAS MARIAS'),
    ('LAS PIEDRAS', 'LAS PIEDRAS'),
    ('LOIZA', 'LOIZA'),
    ('LUQUILLO', 'LUQUILLO'),
    ('MANATI', 'MANATI'),
    ('MARICAO', 'MARICAO'),
    ('MAUNABO', 'MAUNABO'),
    ('MAYAGUEZ', 'MAYAGUEZ'),
    ('MOCA', 'MOCA'),
    ('MOROVIS', 'MOROVIS'),
    ('NAGUABO', 'NAGUABO'),
    ('NARANJITO', 'NARANJITO'),
    ('OROCOVIS', 'OROCOVIS'),
    ('PATILLAS', 'PATILLAS'),
    ('PEÑUELAS', 'PEÑUELAS'),
    ('PONCE I', 'PONCE I'),
    ('PONCE II', 'PONCE II'),
    ('PONCE III', 'PONCE III'),
    ('QUEBRADILLAS', 'QUEBRADILLAS'),
    ('RINCON', 'RINCON'),
    ('RIO GRANDE', 'RIO GRANDE'),
    ('SABANA GRANDE', 'SABANA GRANDE'),
    ('SALINAS', 'SALINAS'),
    ('SAN GERMAN', 'SAN GERMAN'),
    ('SAN JUAN I', 'SAN JUAN I'),
    ('SAN JUAN II', 'SAN JUAN II'),
    ('SAN JUAN III', 'SAN JUAN III'),
    ('SAN JUAN IV', 'SAN JUAN IV'),
    ('SAN JUAN V', 'SAN JUAN V'),
    ('SAN LORENZO', 'SAN LORENZO'),
    ('SAN SEBASTIAN', 'SAN SEBASTIAN'),
    ('SANTA ISABEL', 'SANTA ISABEL'),
    ('TOA ALTA', 'TOA ALTA'),
    ('TOA BAJA', 'TOA BAJA'),
    ('TRUJILLO ALTO', 'TRUJILLO ALTO'),
    ('UTUADO', 'UTUADO'),
    ('VEGA ALTA', 'VEGA ALTA'),
    ('VEGA BAJA', 'VEGA BAJA'),
    ('VIEQUES', 'VIEQUES'),
    ('VILLALBA', 'VILLALBA'),
    ('YABUCOA', 'YABUCOA'),
    ('YAUCO', 'YAUCO'),
    )

    nombre = models.CharField(max_length=200, choices=nombre_choices)

    def __str__(self):
        return self.nombre


class Escuela(models.Model):
    phone_regex = RegexValidator(
                    regex='^\([0-9]{3}\) [0-9]{3}-[0-9]{4}$',
                    message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'."
                    )

    nivel_choices = (
        ('Elemental', 'Elemental'),
        ('Superior', 'Superior'),
        ('Intermedio', 'Intermedio'),
        ('Segunda Unidad', 'Segunda Unidad'),
        ('Todos los niveles', 'Todos los niveles'),
    )

    tipo_choices = (
        ('Regular', 'Regular'),
        ('Educacion Especial', 'Educacion Especial'),
        ('Pre-vocaiconal', 'Pre-vocacional'),
        ('Especializada', 'Especializada'),
        ('Vocacional', 'Vocacional'),
    )

    zona_choices = (
        ('URBANA', 'URBANA'),
        ('RURAL', 'RURAL'),
    )

    operacional_choices = (
        ('SI', 'SI'),
        ('NO', 'NO'),
    )

    # Datos de usuario que genera el registro
    usuario = models.ForeignKey('auth.User', on_delete=models.CASCADE, null=True, blank=True)

    # Datos generales de la escuela
    codigo = models.IntegerField(default=0, primary_key=True)
    nombre = models.CharField(max_length=200)
    telefono = models.CharField(validators=[phone_regex], max_length=200, default='(000) 000-0000')
    fax = models.CharField(validators=[phone_regex], max_length=200, default='(000) 000-0000')
    region_educativa = models.CharField(max_length=200)
    distrito_escolar = models.CharField(max_length=200)
    municipio_escolar = models.CharField(max_length=200, null=True, blank=True)
    direccion_fisica = models.CharField(max_length=200, null=True, blank=True)
    direccion_zipcode = models.CharField(max_length=200, null=True, blank=True)
    #geolocalizacion = models.PointField(null=True, blank=True)
    zona = models.CharField(max_length=200, choices=zona_choices, default='RURAL')
    operacional = models.CharField(max_length=200, choices=operacional_choices, default='SI')
    nivel = models.CharField(max_length=200, choices=nivel_choices, default='Elemental')
    grados = models.CharField(max_length=200, null=True, blank=True)
    tipo = models.CharField(max_length=200, choices=tipo_choices, default='Regular')
    email = models.EmailField(max_length=254, null=True, blank=True)

    # Datos de creacion y modificacion del registro
    fecha_creacion = models.DateTimeField(default=timezone.now)
    fecha_modificacion = models.DateField(auto_now=True)


    def __str__(self):
        return self.nombre


class Personal(models.Model):
    phone_regex = RegexValidator(
                    regex='^\([0-9]{3}\) [0-9]{3}-[0-9]{4}$',
                    message="El telefono debe ser suministrado con el siguiente formato: '(787) 549-1004'."
                    )

    estado_director_choices = (
        ('En propiedad', 'En propiedad'),
        ('Interino', 'Interino'),
    )

    #Foreign Key de escuela
    escuela = models.OneToOneField(Escuela, primary_key=True, on_delete=models.CASCADE)

    #Datos generales del Personal Administrativo de la Escuela
    nombre_del_director = models.CharField(max_length=200, blank=True, null=True)
    estado_del_director = models.CharField(max_length=200, choices=estado_director_choices, blank=True, null=True)
    email_del_director = models.EmailField(max_length=254, null=True, blank=True)
    telefono_del_director = models.CharField(validators=[phone_regex], max_length=200, default='(000) 000-0000', blank=True, null=True)
    nombre_del_consejero = models.CharField(max_length=200, blank=True, null=True)
    email_del_consejero = models.EmailField(max_length=254, blank=True, null=True)
    telefono_del_consejero = models.CharField(validators=[phone_regex], max_length=200, default='(000) 000-0000', blank=True, null=True)
    nombre_del_trabajador_social = models.CharField(max_length=200, blank=True, null=True)
    email_del_trabajador_social = models.EmailField(max_length=254, blank=True, null=True)
    telefono_del_trabajador_social = models.CharField(validators=[phone_regex], max_length=200, default='(000) 000-0000', blank=True, null=True)
    nombre_del_requisante = models.CharField(max_length=200, blank=True, null=True)
    email_del_requisante = models.EmailField(max_length=254, blank=True, null=True)
    telefono_del_requisante = models.CharField(validators=[phone_regex], max_length=200, default='(000) 000-0000', blank=True, null=True)
    nombre_del_presidente_del_consejo_escolar = models.CharField(max_length=200, blank=True, null=True)
    telefono_del_presidente_del_consejo_escolar = models.CharField(validators=[phone_regex], max_length=200, default='(000) 000-0000', blank=True, null=True)


    # Datos de creacion y modificacion del registro
    fecha_creacion = models.DateTimeField(default=timezone.now)
    fecha_modificacion = models.DateField(auto_now=True)

    def __str__(self):
        return "Personal Administrativo de " + self.escuela.nombre

class Matricula(models.Model):
    #Foreign Key de escuela
    escuela = models.OneToOneField(Escuela, primary_key=True, on_delete=models.CASCADE)

    #Datos generales de la matricula de la escuela
    matricula_de_estudiantes = models.IntegerField(default=0, blank=True, null=True)
    grado_infant = models.IntegerField(default=0, blank=True, null=True)
    grado_toddler = models.IntegerField(default=0, blank=True, null=True)
    grado_pk = models.IntegerField(default=0, blank=True, null=True)
    grado_pke = models.IntegerField(default=0, blank=True, null=True)
    grado_pkm = models.IntegerField(default=0, blank=True, null=True)
    grado_k = models.IntegerField(default=0, blank=True, null=True)
    grado_1 = models.IntegerField(default=0, blank=True, null=True)
    grado_2 = models.IntegerField(default=0, blank=True, null=True)
    grado_3 = models.IntegerField(default=0, blank=True, null=True)
    grado_4 = models.IntegerField(default=0, blank=True, null=True)
    grado_5 = models.IntegerField(default=0, blank=True, null=True)
    grado_6 = models.IntegerField(default=0, blank=True, null=True)
    grado_SGE = models.IntegerField(default=0, blank=True, null=True)
    grado_7 = models.IntegerField(default=0, blank=True, null=True)
    grado_8 = models.IntegerField(default=0, blank=True, null=True)
    grado_9 = models.IntegerField(default=0, blank=True, null=True)
    grado_SGI = models.IntegerField(default=0, blank=True, null=True)
    grado_10 = models.IntegerField(default=0, blank=True, null=True)
    grado_11 = models.IntegerField(default=0, blank=True, null=True)

CATEDRA/forms.py
from dal import autocomplete
from django import forms
from django.forms import SelectMultiple

from .models import Escuela, Personal, Matricula, Actividad, Destreza, Presupuesto, Visita, Propuesta, Ofrecimiento, PurchaseOrder, Factura

class EscuelaForm(forms.ModelForm):

    class Meta:
        model = Escuela
        fields = ('codigo', 'nombre', 'telefono', 'fax', 'region_educativa', 'municipio_escolar', 'nivel',  'tipo')

class PersonalForm(forms.ModelForm):

    class Meta:
        model = Personal
        fields = ('nombre_del_director', 'estado_del_director', 'email_del_director', 'telefono_del_director', 'nombre_del_consejero', 'email_del_consejero', 'telefono_del_consejero', 'nombre_del_trabajador_social', 'email_del_trabajador_social', 'telefono_del_trabajador_social', 'nombre_del_requisante', 'email_del_requisante', 'telefono_del_requisante', 'nombre_del_presidente_del_consejo_escolar', 'telefono_del_presidente_del_consejo_escolar')

class MatriculaForm(forms.ModelForm):

    class Meta:
        model = Matricula
        fields = ('matricula_de_estudiantes', 'maestros_de_espanol', 'maestros_de_matematicas', 'maestros_de_ingles', 'maestros_de_ciencias', 'maestros_otros')

class DestrezaForm(forms.ModelForm):

    class Meta:
        model = Destreza
        fields = ('espanol', 'matematicas', 'ingles', 'prioridad', 'materia_prioridad')

class PresupuestoForm(forms.ModelForm):

    class Meta:
        model = Presupuesto
        fields = ('presupuesto_asignado',)


class VisitaForm(forms.ModelForm):
    class Meta:
        model = Visita
        fields = ('escuela', 'anotaciones', 'hoja_de_visita',)

class ActividadForm(forms.ModelForm):

    class Meta:
        model = Actividad
        fields = ('estado', 'tipo', 'taller_sugerido', 'fecha', 'horario',)

class PropuestaForm(forms.ModelForm):

    class Meta:
        model = Propuesta
        fields = ('tipo', 'escuela', 'fecha', 'estado', 'necesidad', 'descripcion')

class OfrecimientoForm(forms.ModelForm):

    class Meta:
        model = Ofrecimiento
        fields = ('codigode', 'materia', 'estrategia', 'titulo', 'horas', 'participantes', )

class PurchaseOrderForm(forms.ModelForm):

    class Meta:
        model = PurchaseOrder
        fields = ('numero', 'ofrecimiento', 'documento',)

class FacturaForm(forms.ModelForm):

    class Meta:
        model = Factura
        fields = ('numero', 'fecha', 'monto',)

CATEDRA/templates/CATEDRA/PO_detalle.html
{% extends 'CATEDRA/base.html' %}

{% block content %}
<div class="contenido" style="display: none">
  <div class="row grid-responsive">
    <div class="column page-heading">
      <div class="large-card clearfix">
        <div class="float-left">
          <h2>PO No. {{po.pk}} - Escuela {{po.propuesta.escuela.nombre}}</h2>

          <em>Creado en {{po.fecha}}</em>
          <br>
          <br>

        </div>

      </div>
    </div>
  </div>

  <div class="row grid-responsive">
    <div class="column">
      <div class="card">
        <div class="card-title clearfix">
          <h2 class="float-left">Ofrecimientos</h2>
        </div> <!-- End card-title -->
        <div class="card-block">
          <table>
            <thead>
              <th>Estado</th>
              <th>Cantidad</th>
              <th class="ofrecimiento-materia">Materia</th>
              <th>Modalidad/Codigo</th>
              <th class="ofrecimiento-estrategia">Estrategia</th>
              <th class="ofrecimiento-titulo">Titulo</th>
              <th class="ofrecimiento-horas">Horas</th>
              <th>Costo</th>
              <th>Total</th>

            </thead>
            <tbody>
              {% for ofrecimiento in ofrecimientos %}
              <tr>
                <td>{{ofrecimiento.estado}}</td>
                {% if ofrecimiento.codigode.codigo == 11829 %}
                <td>{{ofrecimiento.participantes}}</td>
                {% else %}
                <td>1</td>
                {% endif %}
                <td class="ofrecimiento-materia">{{ofrecimiento.materia}}</td>
                <td>{{ofrecimiento.codigode}}</td>
                <td class="ofrecimiento-estrategia">{{ofrecimiento.estrategia}}</td>
                <td class="ofrecimiento-titulo">{{ofrecimiento.titulo}}</td>
                <td class="ofrecimiento-horas">{{ofrecimiento.horas}}</td>
                <td>${{ofrecimiento.codigode.costo|format_thousands}}</td>
                {% if ofrecimiento.codigode.codigo == 11829 %}
                <td>${{ofrecimiento.codigode.costo|multiply:ofrecimiento.participantes|format_thousands}}</td>
                {% else %}
                <td>${{ofrecimiento.codigode.costo|format_thousands}}</td>
                {% endif %}
              {% endfor %}
              <tr>

                <td></td>
                <td></td>
                <td class="ofrecimiento-materia"></td>
                <td></td>
                <td class="ofrecimiento-estrategia"></td>
                <td class="ofrecimiento-titulo"></td>
                <td class="ofrecimiento-horas"></td>
                <td><strong>Total</strong></td>
                <td><strong>${{costo_total|format_thousands}}</strong></td>

              </tr>
            </tbody>
          </table>
        </div> <!-- End card-block -->
      </div> <!-- End card -->
    </div> <!--End column -->
  </div> <!-- End row -->

  <div class="row grid-responsive">
    <div class="column">
      <div class="card">
        <div class="card-title clearfix">
          <h2 class="float-left">Facturas</h2>
          <a class="button float-right" href="{% url 'crear_factura' numero_po=po.numero %}"><span class="fa fa-plus"></span> Agregar</a>
        </div> <!-- End card-title -->
        <div class="card-block">
          <table>
            <thead>
              <th>Numero QB</th>
              <th>Fecha</th>
              <th>Monto</th>
            </thead>
            <tbody>
              {% for factura in facturas %}
              <tr>
                <td>{{factura.numero}}</td>
                <td>{{factura.fecha}}</td>
                <td>{{factura.monto}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div> <!-- End card-block -->
      </div> <!-- End card -->
    </div> <!--End column -->
  </div> <!-- End row -->

</div>


{% endblock %}

CATEDRA/templates/CATEDRA/catalogo_servicios.html
{% extends 'CATEDRA/base.html' %}

{% block content %}
<div class="contenido" style="display: none;">
  <div class="row grid-responsive">
    <div class="column ">
      <div class="card">
        <div class="card-title clearfix">
          <h3 class="float-left">Catalogo de servicios</h3>
        </div>
        <div class="card-block">
          <table id="" class="display">
            <thead>
              <tr>
                <th>Tipo</th>
                <th>Estategia/Enfoque</th>
                <th>Titulo</th>
              </tr>
            </thead>
            <tbody>
              {% for servicio in servicios %}
                <tr>
                  <td>{{servicio.tipo}}</td>
                  <td>{{servicio.estrategia}}</td>
                  <td>{{servicio.titulo}}</td>
                </tr>
              {% endfor %}
            </tbody>
            <tfoot>
              <tr>
                <th>Tipo</th>
                <th>Estrategia/Enfoque</th>
                <th>Titulo</th>
              </tr>
          </tfoot>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

CATEDRA/templates/CATEDRA/escuela_edit.html
{% extends 'CATEDRA/base.html' %}

{% block content %}
<div class="contenido" style="display: none;">
  <div class="row grid-responsive">
    <div class="column page-heading">
      <div class="card">
        <div class="card-title">
          <h3>Información de la escuela</h3>
        </div> <!-- End card-title -->
        <div class="card-block">
          <form method="POST" class="post-form">{% csrf_token %}
            {{form}}
            <br/>
            <button type="submit"><span class="fa fa-save"></span> Guardar</button>
          </form>
        </div> <!-- End card-block -->
      </div> <!-- End card -->
    </div> <!-- End column -->
  </div> <!-- End row -->
</div>


{% endblock %}

CATEDRA/templates/CATEDRA/inicio.html
{% extends 'CATEDRA/base.html' %}

{% block content %}
<div class="contenido" style="display: none;">
  <div class="row grid-responsive">
    <div class="column page-heading">
      <div class="large-card clearfix">
        <div class="float-left">
          <h2>GEEO/CATEDRA</h2>
          <em>Demo creado por: Wellington Abreu </em>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

CATEDRA/templates/CATEDRA/ofrecimiento_edit.html
{% extends 'CATEDRA/base.html' %}

{% block content %}
<div class="contenido" style="display: none;">
  <div class="row grid-responsive">
    <div class="column page-heading">
      <div class="card">
        <div class="card-title">
          <h3>Información de ofrecimiento</h3>
        </div> <!-- End card-title -->
        <div class="card-block">
          {% if request_type != 'edit' %}
          <form enctype="multipart/form-data" method="POST" class="post-form">{% csrf_token %}
            <!--
            <div class="fieldWrapper">
              <label for="id_estado">Estado:</label>
              <select name="estado" id="id_estado">
                <option value="EN EVALUACION">EN EVALUACION</option>
                <option value="APROBADA">APROBADA</option>
                <option value="RECHAZADA">RECHAZADA</option>
              </select>
            </div>
          -->
            <div class="fieldWrapper">
              <label for="id_codigode">Codigo Departamento Educacion:</label>
              <select name="codigode" required id="id_codigode">
                <option value selected> ---------- </option>
                {% for codigo in codigosde %}
                <option value="{{codigo.codigo}}">{{codigo}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="fieldWrapper">
              <label for="id_materia">Materia:</label>
              <input type="text" name="materia" maxlength="200" required id="id_materia">
            </div>
            <div class="fieldWrapper">
              <label for="id_estrategia">Estategia/Enfoque:</label>
              <select name="estrategia" required id="id_estrategia">
                <option value selected> ---------- </option>
                {% for estrategia in estrategias %}
                <option value="{{estrategia|lookup:'estrategia'}}">{{estrategia|lookup:'estrategia'}}</option>
                {% endfor %}
              </select>
            </div>
            <div class="fieldWrapper">
              <label for="id_titulo">Titulo:</label>
              <select name="titulo" required id="id_titulo" disabled="True">
                <option value selected> Seleccione una Estrategia o Enfoque </option>
                <!--
                {% for titulo in titulos %}
                <option value="{{titulo|lookup:'titulo'}}">{{titulo|lookup:'titulo'}}</option>
                {% endfor %}
              -->
              </select>
            </div>
            <div class="fieldWrapper">
              <label for="id_horas">Horas:</label>
              <input type="number" name="horas" value="0" required id="id_horas">
            </div>
            <div class="fieldWrapper">
              <label for="id_participantes">Participantes:</label>
              <input type="number" name="participantes" value="0" required id="id_horas">
            </div>
            <br/>
            <button type="submit"><span class="fa fa-save"></span> Guardar</button>
          </form>
          {% else %}
            {{form}}
            <br/>
            <button type="submit"><span class="fa fa-save"></span> Guardar</button>
          {% endif %}
        </div> <!-- End card-block -->
      </div> <!-- End card -->
    </div> <!-- End column -->
  </div> <!-- End row -->
</div>


{% endblock %}